"""initial_schema_setup_mysql

Revision ID: 6847f8cf1fed
Revises:
Create Date: 2025-07-12 00:47:02.951122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6847f8cf1fed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('super_admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_super_admins_email'), 'super_admins', ['email'], unique=True)
    op.create_index(op.f('ix_super_admins_id'), 'super_admins', ['id'], unique=False)
    op.create_index(op.f('ix_super_admins_username'), 'super_admins', ['username'], unique=True)

    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('data_limit_gb', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)

    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_super_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_super_admin_id'], ['super_admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)

    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('gateway', sa.String(length=50), nullable=False),
    sa.Column('gateway_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_initiated_at', sa.DateTime(), nullable=True),
    sa.Column('payment_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('raw_request_payload', sa.JSON(), nullable=True),
    sa.Column('raw_response_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_admin_id'), 'payment_transactions', ['admin_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_gateway_transaction_id'), 'payment_transactions', ['gateway_transaction_id'], unique=True)
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_status'), 'payment_transactions', ['status'], unique=False)

    op.create_table('vpn_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('marzban_user_id', sa.String(length=255), nullable=True),
    sa.Column('abresani_user_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_link', sa.Text(), nullable=True),
    sa.Column('qr_code_link', sa.Text(), nullable=True),
    sa.Column('data_usage_gb', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vpn_users_abresani_user_id'), 'vpn_users', ['abresani_user_id'], unique=False)
    op.create_index(op.f('ix_vpn_users_created_by_admin_id'), 'vpn_users', ['created_by_admin_id'], unique=False)
    op.create_index(op.f('ix_vpn_users_id'), 'vpn_users', ['id'], unique=False)
    op.create_index(op.f('ix_vpn_users_marzban_user_id'), 'vpn_users', ['marzban_user_id'], unique=False)
    op.create_index(op.f('ix_vpn_users_plan_id'), 'vpn_users', ['plan_id'], unique=False)
    op.create_index(op.f('ix_vpn_users_username'), 'vpn_users', ['username'], unique=False)

    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('super_admin_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['super_admin_id'], ['super_admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['vpn_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_logs_action_type'), 'action_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_action_logs_admin_id'), 'action_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_action_logs_id'), 'action_logs', ['id'], unique=False)
    op.create_index(op.f('ix_action_logs_super_admin_id'), 'action_logs', ['super_admin_id'], unique=False)
    op.create_index(op.f('ix_action_logs_target_user_id'), 'action_logs', ['target_user_id'], unique=False)
    op.create_index(op.f('ix_action_logs_timestamp'), 'action_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_logs_timestamp'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_target_user_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_super_admin_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_admin_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_action_type'), table_name='action_logs')
    op.drop_table('action_logs')

    op.drop_index(op.f('ix_vpn_users_username'), table_name='vpn_users')
    op.drop_index(op.f('ix_vpn_users_plan_id'), table_name='vpn_users')
    op.drop_index(op.f('ix_vpn_users_marzban_user_id'), table_name='vpn_users')
    op.drop_index(op.f('ix_vpn_users_id'), table_name='vpn_users')
    op.drop_index(op.f('ix_vpn_users_created_by_admin_id'), table_name='vpn_users')
    op.drop_index(op.f('ix_vpn_users_abresani_user_id'), table_name='vpn_users')
    op.drop_table('vpn_users')

    op.drop_index(op.f('ix_payment_transactions_status'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_gateway_transaction_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_admin_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')

    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')

    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')

    op.drop_index(op.f('ix_super_admins_username'), table_name='super_admins')
    op.drop_index(op.f('ix_super_admins_id'), table_name='super_admins')
    op.drop_index(op.f('ix_super_admins_email'), table_name='super_admins')
    op.drop_table('super_admins')
    # ### end Alembic commands ###
